In [19]:
from __future__ import print_function
import torch
torch.__version__

'0.1.12_2'

In [20]:
x = torch.Tensor(5, 3)
x


 5.6568e-03  4.5867e-41  5.6568e-03
 4.5867e-41  1.8047e-09  4.5867e-41
 1.8047e-09  4.5867e-41  1.8047e-09
 4.5867e-41  1.8048e-09  4.5867e-41
 1.8048e-09  4.5867e-41  1.8048e-09
[torch.FloatTensor of size 5x3]

In [21]:
x = torch.rand(5, 3)
x


 0.0214  0.4890  0.1133
 0.3366  0.9882  0.6367
 0.0638  0.9697  0.0119
 0.6355  0.2086  0.1976
 0.5936  0.4347  0.5663
[torch.FloatTensor of size 5x3]

In [22]:
x.size()

torch.Size([5, 3])

In [23]:
y = torch.rand(5, 3)
x + y


 0.1831  1.3220  0.2237
 0.8589  1.5652  0.6988
 0.6219  1.7465  0.6751
 1.3788  0.8308  0.3738
 1.1621  0.5986  1.3679
[torch.FloatTensor of size 5x3]

In [24]:
torch.add(x, y)


 0.1831  1.3220  0.2237
 0.8589  1.5652  0.6988
 0.6219  1.7465  0.6751
 1.3788  0.8308  0.3738
 1.1621  0.5986  1.3679
[torch.FloatTensor of size 5x3]

In [25]:
result = torch.Tensor(5, 3) # output tensor
torch.add(x, y, out=result)
result


 0.1831  1.3220  0.2237
 0.8589  1.5652  0.6988
 0.6219  1.7465  0.6751
 1.3788  0.8308  0.3738
 1.1621  0.5986  1.3679
[torch.FloatTensor of size 5x3]

In [26]:
y.add_(x) # in-place operation


 0.1831  1.3220  0.2237
 0.8589  1.5652  0.6988
 0.6219  1.7465  0.6751
 1.3788  0.8308  0.3738
 1.1621  0.5986  1.3679
[torch.FloatTensor of size 5x3]

In [27]:
a = torch.ones(5)
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [28]:
b = a.numpy()
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

In [29]:
a.add_(1) # referencial - change a will change the numpy array
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [30]:
import numpy as np
a = np.ones(5)
a

array([ 1.,  1.,  1.,  1.,  1.])

In [31]:
b = torch.from_numpy(a)
np.add(a, 1, out=a) # same here but the otherway around
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [32]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x + y)


 0.2045  1.8110  0.3370
 1.1955  2.5534  1.3354
 0.6858  2.7162  0.6869
 2.0143  1.0395  0.5714
 1.7557  1.0333  1.9342
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]



In [33]:
from torch.autograd import Variable

In [34]:
x = Variable(torch.ones(2, 2), requires_grad=True)
x

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [35]:
y = x + 2
y

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]

In [36]:
y.creator

In [37]:
z = y * y * 3
out = z.mean()
print(z, out)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



In [39]:
out.backward()

In [40]:
x.grad

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]